services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src
    ports:
      - "9004:9004"
    environment:
      - JUPYTER_ENEBLE_LAB=yes
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=9004", "--allow-root", "--no-browser", "--NotebookApp.password=' argon2:$$argon2id$$v=19$$m=10240,t=10,p=8$$f+ZQrIEjs8xuiBD7i22zWQ$$X3FjYyolj3kuzs6zQ512NpuazlLvUaIFQgVSD0YRcXI '"]
